package Leetcode;

import java.util.ArrayList;

/**
 * Created by z.g.13@163.com on 2016/9/8.
 *
 Given two strings s and t which consist of only lowercase letters.
 String t is generated by random shuffling string s and then add one more letter at a random position.
 Find the letter that was added in t.

 Input:
 s = "abcd"
 t = "abcde"

 Output:
 e

 Explanation:
 'e' is the letter that was added.

 O(n^2) 双循环判断
 O(2n) 使用列表去重
 */
public class Solution
{
    public char findTheDifference(String s, String t)
    {
        ArrayList<Character> al = new ArrayList<>();
        for(int i = 0;i<t.length();i++)
            al.add(t.charAt(i));
        System.out.println(al);
        for(int i = 0;i<s.length();i++)
        {
            if (s.contains(al.get(i)))
        }
        //al.remove('a');
        al.remove('a');
        System.out.println(al);

        return al.get(0);
    }

    // hash表
    public char findTheDifference(String s, String t) {
        int[] hash = new int[26];
        char[] sarray = s.toCharArray();
        char[] tarray = t.toCharArray();
        for(int i = 0; i < s.length(); i++){
            int num = sarray[i] - 'a';
            hash[num]++;
        }
        for(int i = 0; i < t.length(); i++){
            int tnum = tarray[i] - 'a';
            hash[tnum]--;
            if(hash[tnum] < 0){
                return (char) ((char)tnum+'a');
            }
        }
        return '-';
    }
}